name: jsonrpc
description: JSON RPC 2.0 for dart language.
version: 1.0.1
repository: https://github.com/yangentao/json_rpc
homepage: https://github.com/yangentao/json_rpc

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  #  entao_dutil: ^2.0.5
  entao_log: ^1.2.8
  entao_lint: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
